// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PIYA_API.Data;

#nullable disable

namespace PIYA_API.Migrations
{
    [DbContext(typeof(PharmacyApiDbContext))]
    [Migration("20260328120000_MigrateToUtcTimestamps")]
    partial class MigrateToUtcTimestamps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
            => AddAppointmentRescheduledToId.BuildUtcMigrationTargetModel(modelBuilder);
    }
}
